# Generated by Django 5.2 on 2025-09-18 02:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cita', '0001_initial'),
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='citaventa',
            name='cliente_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuario.cliente'),
        ),
        migrations.AddField(
            model_name='citaventa',
            name='manicurista_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuario.manicurista'),
        ),
        migrations.AddField(
            model_name='citaventa',
            name='estado_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cita.estadocita'),
        ),
        migrations.AddField(
            model_name='serviciocita',
            name='cita_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cita.citaventa'),
        ),
    ]
