# Generated by Django 5.2 on 2025-09-18 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_persona', models.CharField(choices=[('NATURAL', 'Natural'), ('JURIDICA', 'Jurídica')], max_length=10)),
                ('tipo_documento', models.CharField(choices=[('NIT', 'NIT'), ('CC', 'Cédula de Ciudadanía'), ('CE', 'Cédula de Extranjería')], max_length=3)),
                ('numero_documento', models.CharField(max_length=15, unique=True)),
                ('nombre_empresa', models.CharField(blank=True, max_length=60, null=True)),
                ('telefono', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=60, unique=True)),
                ('direccion', models.CharField(max_length=60)),
                ('ciudad', models.CharField(max_length=60)),
                ('nombre_representante', models.CharField(blank=True, max_length=60, null=True)),
                ('apellido_representante', models.CharField(blank=True, max_length=60, null=True)),
                ('telefono_representante', models.CharField(blank=True, max_length=15, null=True)),
                ('email_representante', models.EmailField(blank=True, max_length=60, null=True)),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=10)),
            ],
        ),
    ]
