# Generated by Django 5.2 on 2025-09-18 02:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Permiso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modulo', models.CharField(default='', max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='no ingresado', max_length=60)),
                ('descripcion', models.CharField(default='no hay descripcion', max_length=80, null=True)),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Permiso_Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permiso_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rol.permiso')),
                ('rol_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rol.rol')),
            ],
            options={
                'unique_together': {('rol_id', 'permiso_id')},
            },
        ),
    ]
