# Generated by Django 5.2 on 2025-09-18 05:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('insumo', '0001_initial'),
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Abastecimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('Sin reportar', 'Sin Reportar'), ('Reportado', 'Reportado')], default='Sin reportar', max_length=30)),
                ('fecha_reporte', models.DateField(blank=True, null=True)),
                ('manicurista_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.manicurista')),
            ],
        ),
        migrations.CreateModel(
            name='InsumoAbastecimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=1)),
                ('estado', models.CharField(choices=[('Acabado', 'Acabado'), ('Uso medio', 'Uso medio'), ('Bajo', 'Bajo'), ('Sin usar', 'Sin usar')], default='Sin usar', max_length=30)),
                ('comentario', models.TextField(blank=True, null=True)),
                ('abastecimiento_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abastecimiento.abastecimiento')),
                ('insumo_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insumo.insumo')),
            ],
        ),
    ]
