# Generated by Django 5.2 on 2025-09-18 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Liquidacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FechaInicial', models.DateField()),
                ('TotalGenerado', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('Comision', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('Local', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('FechaFinal', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Novedades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha', models.DateField()),
                ('HoraEntrada', models.TimeField()),
                ('HoraSalida', models.TimeField()),
                ('Motivo', models.TextField()),
            ],
        ),
    ]
