# Generated by Django 5.2 on 2025-09-18 02:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manicurista', '0001_initial'),
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='liquidacion',
            name='manicurista_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.manicurista'),
        ),
        migrations.AddField(
            model_name='novedades',
            name='manicurista_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.manicurista'),
        ),
    ]
